# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "super-ebs-pruner-9000"
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["W. Andrew Loe III"]
  s.date = "2011-10-17"
  s.description = "Thins EBS volume snapshots."
  s.email = "andrew@andrewloe.com"
  s.executables = ["pruner"]
  s.files = [
    "Rakefile",
    "VERSION",
    "bin/pruner",
    "lib/pruner.rb",
    "lib/pruner/silence_ssl_warning.rb",
    "lib/pruner/version.rb",
    "super-ebs-pruner-9000.gemspec",
    "test/test_pruner.rb"
  ]
  s.homepage = "http://github.com/loe/super-ebs-pruner-9000"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Thins EBS volume snapshots."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<right_aws>, ["~> 1.10.0"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 2.3"])
    else
      s.add_dependency(%q<right_aws>, ["~> 1.10.0"])
      s.add_dependency(%q<activesupport>, ["~> 2.3"])
    end
  else
    s.add_dependency(%q<right_aws>, ["~> 1.10.0"])
    s.add_dependency(%q<activesupport>, ["~> 2.3"])
  end
end

